;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = color.ini
include-file = module.ini

[bar/mybar]
width = 100%
height = 24pt

background = ${colors.nord0}
foreground = ${colors.nord4}

line-size = 3pt

padding-left = 0
padding-right = 1

border-top = 4pt
border-left = 4pt
border-right  = 4pt

module-margin = 1

font-0 = JetBrainsMonoNerdFont;2

modules-left = xworkspaces xwindow
modules-center = date
modules-right = cpu memory filesystem pulseaudio wlan eth

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
